### ISSUE TITLE
getCircuitAsSVG() API gives undefined

### ISSUE THREAD

**Issue by Romaxx** [sharpie7/circuitjs1#1015]
Hi,

I've tried local and falstad website getCircuitAsSVG() API function from javascript but it return "undefined" in the two cases.
export to SVG in the menu working (in base64 form) in the two cases.. I don't understand what's the problem. 

Any Help :) ?

**Comment by pfalstad** [comment]
Sorry, there's an error in the doc.  It's asynchronous, because the package that does the SVG conversion may need to be initialized and that is asychronous.

function svgRendered(sim, svg) {
  console.log('here is svg data:', svg);
}
sim.onsvgrendered = svgRendered;
sim.getCircuitAsSVG();

See here for an example:

https://www.falstad.com/circuit/jsinterface.html

**Comment by Romaxx** [comment]
That was a fast reply 🙂 Thanks a lot, it’s working perfectly now! Also, thank you for CircuitJS it’s an amazing tool !

**Comment by esaruoho** [comment]
This was resolved in the comments — the SVG API is asynchronous and requires using the `onsvgrendered` callback. Paul's example in the comments above shows the correct usage pattern.

**Comment by pfalstad** [comment]
The doc is still wrong.

https://www.falstad.com/circuit/doc/js-interface.html

**Comment by pfalstad** [comment]
doc is fixed
